#!/bin/zsh
#
#   This file is part of CHC Ninja.
#   https://github.com/crymesomecrypto/chcninja-ctl
#
#   CHC Ninja is free software: you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation, either version 3 of the License, or
#   (at your option) any later version.
#
#   CHC Ninja is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with CHC Ninja.  If not, see <http://www.gnu.org/licenses/>.
#

# Disable logging by default
blockdegapperlog=/dev/null
blockparserlog=/dev/null
blocksjsonlog=/dev/null

# If parameter 1 is log then enable logging
if [[ "$1" == "log" ]]; then
  blockdegapperlog=/var/log/cmn/blockdegapper.log
  blocksjsonlog=/var/log/cmn/blocksjson.log
fi

# Sequentially run scripts
/usr/bin/nice -n 14 /opt/cmnctl/cmnblockdegapper main >> $blockdegapperlog
/usr/bin/nice -n 14 /opt/cmnctl/cmnblockparser >> $blockparserlog
/usr/bin/nice -n 14 /usr/bin/php /var/www/chcninja/api/cron.php main blocks24h >> $blocksjsonlog
/usr/bin/nice -n 14 /usr/bin/php /var/www/chcninja/api/cron.php main blockssuperblocks >> $blocksjsonlog
